
import 'bootstrap/dist/css/bootstrap.css';
// import 'bootstrap-rtl/dist/css/bootstrap-rtl.min.css';
// import './global-RTL.css'
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import rtlPlugin from 'stylis-plugin-rtl';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
      <body >{children}</body>
    </html>
    // dir="rtl"
  );
}
