"use client";
// import 'bootstrap/dist/css/bootstrap.css';
// import 'bootstrap-rtl/dist/css/bootstrap-rtl.min.css';
import './global-RTL.css'
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import rtlPlugin from 'stylis-plugin-rtl';
import React, { createContext, useEffect, useState } from "react";


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const LanguageContext = createContext();

export default function RootLayout({ children }) {
  const lang = typeof window !== "undefined" ? localStorage.getItem("selectedLanguage") || "en" : "en"
  const [selectedLanguage, setSelectedLanguage] = useState(lang);
  useEffect(() => {
    localStorage.setItem("selectedLanguage", selectedLanguage);
  }, [selectedLanguage]);

  const value = {
    selectedLanguage,
    setSelectedLanguage,
  };
  
  return (
    <LanguageContext.Provider value={value}>
      <html lang={selectedLanguage}>
        {/* <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> */}
        <body dir={selectedLanguage === "ar" ? "rtl" : "ltr"}>
          {children}
        </body>
      </html>
    </LanguageContext.Provider>
  );
}
